### ISSUE TITLE
Quiz Question: Handle leaving of quiz

### ISSUE THREAD

**Issue by hzxcaryn** [donjar/quizard#137]
Double confirm leaving with alert.
Let them know that they can continue the quiz anytime they want.

**Comment by robertbegna** [comment]
hey, I'd like to work on this

**Comment by hzxcaryn** [comment]
@robertbegna Hey thank you for your interest! However this project is still currently part of our school project that we need to submit soon so I don't think we're open for contributions from others as of now 😢
