### ISSUE TITLE
Which option did I choose ?

### ISSUE THREAD

**Issue by snguyenthanh** [donjar/quizard#153]
Personally, I think it is a bit hard to see which option I chose (Although I know the first option is the correct one).

<img width="795" alt="Screenshot 2019-09-27 at 2 07 52 PM" src="https://user-images.githubusercontent.com/35214933/65749438-42636200-e130-11e9-9e1c-5aa8ed1c52e9.png">

**Comment by alistairong** [comment]
no time. if i didn't choose thailand, would it be wrong?
